import { StyleSheet } from 'react-native';

export const createStyles = (theme, isRTL) => {
  const { colors, typography, spacing } = theme;
  const flexDirection = isRTL ? 'row-reverse' : 'row';

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    center: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    header: {
      flexDirection,
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: spacing.m,
      paddingTop: spacing.xl,
      paddingBottom: spacing.m,
      borderBottomWidth: 1,
      borderBottomColor: colors.glassBorder,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.glass,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.glassBorder,
    },
    headerTitle: {
      ...typography.h2,
      color: colors.text,
    },
    content: {
      padding: spacing.l,
      paddingBottom: spacing.xl,
    },
    card: {
      flexDirection,
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.card,
      borderRadius: 18,
      padding: spacing.l,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      marginBottom: spacing.m,
    },
    cardLeft: {
      flex: 1,
      marginRight: isRTL ? 0 : spacing.m,
      marginLeft: isRTL ? spacing.m : 0,
    },
    cardTitle: {
      ...typography.body,
      fontWeight: 'bold',
      color: colors.text,
    },
    cardSubtitle: {
      ...typography.caption,
      color: colors.textMuted,
      marginTop: 4,
    },
    roundIconButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    sectionLabel: {
      ...typography.caption,
      color: colors.textMuted,
      letterSpacing: 1,
      textTransform: 'uppercase',
      marginTop: spacing.l,
      marginBottom: spacing.s,
    },
    timesCard: {
      backgroundColor: colors.card,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      overflow: 'hidden',
    },
    timeRow: {
      flexDirection,
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: spacing.l,
      paddingVertical: spacing.m,
      borderBottomWidth: 1,
      borderBottomColor: colors.glassBorder,
    },
    timeLeft: {
      flexDirection,
      alignItems: 'center',
      gap: 10,
    },
    timeText: {
      ...typography.body,
      fontWeight: 'bold',
      color: colors.text,
    },
    deleteTimeButton: {
      width: 40,
      height: 40,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    addTimeButton: {
      flexDirection,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      padding: spacing.l,
      borderWidth: 2,
      borderColor: colors.primary,
      margin: spacing.l,
      borderRadius: 14,
      backgroundColor: colors.primary + '08',
    },
    addTimeText: {
      ...typography.body,
      color: colors.primary,
      fontWeight: 'bold',
    },
    muteRow: {
      flexDirection,
      gap: 12,
      marginTop: spacing.s,
    },
    muteChip: {
      flex: 1,
      height: 44,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      backgroundColor: colors.card,
      justifyContent: 'center',
      alignItems: 'center',
    },
    muteChipActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primary + '10',
    },
    muteChipText: {
      ...typography.body,
      color: colors.text,
      fontWeight: '600',
    },
    muteChipTextActive: {
      color: colors.primary,
      fontWeight: 'bold',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.55)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: spacing.l,
    },
    modalCard: {
      width: '100%',
      backgroundColor: colors.card,
      borderRadius: 22,
      padding: spacing.l,
      borderWidth: 1,
      borderColor: colors.glassBorder,
    },
    modalTitle: {
      ...typography.h3,
      color: colors.text,
      textAlign: 'center',
      marginBottom: 6,
    },
    modalSubtitle: {
      ...typography.caption,
      color: colors.textMuted,
      textAlign: 'center',
      marginBottom: spacing.l,
    },
    modalInput: {
      backgroundColor: colors.glass,
      borderRadius: 14,
      padding: spacing.m,
      color: colors.text,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      textAlign: 'center',
      fontWeight: 'bold',
      letterSpacing: 1,
      marginBottom: spacing.l,
    },
    modalButtons: {
      flexDirection,
      gap: 12,
    },
    modalButton: {
      flex: 1,
      height: 48,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
    },
    modalCancel: {
      backgroundColor: colors.glass,
      borderColor: colors.glassBorder,
    },
    modalConfirm: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    modalCancelText: {
      ...typography.body,
      fontWeight: 'bold',
      color: colors.text,
    },
    modalConfirmText: {
      ...typography.body,
      fontWeight: 'bold',
      color: '#FFFFFF',
    },
  });
};

